### ISSUE TITLE
epic: Identifying and handling errors

### ISSUE THREAD

**Issue by aecepoglu** [kamp-us/pano#536]
### What is this epic about?

This is a question and a discussion around if we want to predetermine our error types and:

1. When throwing a `new Error()` , throw a `new SomeSpecificError()` instead
2. Refer to them in tests so we can check if an error looks like a `SomeSpecificError` instead of checking for the error text.
3. Send errors in responses and make our errors more machine readable (thus making teh lives of our clients easier (?))
4. Use them as logic. This is a moot point as in TS we cannot declare the promise rejection types.

A random list of example error types:

* NotFoundError
* AuthenticationError
* DbConnectionError

We'll need to know how specific we want to get. Do we say: `NotFoundError` or `SozlukEntryNotFoundError`

### Tasks for this epic

- [ ] determine if this effort is worth its benefit
- [ ] identify an initial set of errors . Possible starting points: every function that's returning a promise; every entity we have and actions we perform on them
- [ ] establish a pattern for how to throw, catch, extend and test errors

**Comment by usirin** [comment]
Thank you so much for this, i really think this is one of the most overseen parts of building an application or framework.

Note to self: We were using a great error handling pattern at twitch, which involves returning an `error` field in response types. I'll dig into this, and will try to come up with some ideas.

Since GQL is in the middle of "all things related to kampus" we might want to drive our `error` strategy around it.

**Comment by Ketcap** [comment]
I think how it's being communicated to the response needs a resolver for all fields that returns Union that has "error.message" and other fields.

**Comment by usirin** [comment]
https://the-guild.dev/blog/graphql-error-handling-with-fp posting here as ref, probably will end up implementing this, as we are using graphql-yoga stack already.
