### ISSUE TITLE
epic: linter for new sozluk contents

### ISSUE THREAD

**Issue by arabacibahadir** [kamp-us/pano#578]
### What is this epic about?

We aim to enhance the quality of `kampus/sozluk` content by introducing a CI mechanism for automatically assessing the quality of new sozluk contents. This tool would help identify potential issues in the sozluk content, such as sentence length, weasel words, spelling errors, improper capitalization, and redundant abbreviations etc. 
If you have any additional thoughts or ideas, please first share them in the following discussion: https://github.com/kamp-us/monorepo/discussions/563

### Implementation and Integration:
Currently, we do not have an existing sozluk linter system in place, and we will be building this tool from scratch. Our plan is to integrate it into our CI process. This integration will enable the CI system to automatically review and provide feedback on the quality of each sozluk content submitted through pull requests.

### Tasks for this epic

- [ ] Sentence length: Longer sentences can be more challenging to comprehend, so we need to measure the length of sentences and identify excessively long ones.
- [ ] Weasel words: We should avoid using weasel words in sozluk entries.
- [ ] Spell checking: The tool should check for spelling errors and suggest corrections if any are found.
- [ ] Proper capitalization: Ensuring entries have appropriate capitalization to maintain consistency and readability.
- [ ] Redundant abbreviations: Identifying and addressing unnecessary abbreviations.
- [ ] Title-Tag-Content consistency
- [ ] ...

**Comment by fdemir** [comment]
Great point. May we consider about leverage the LLM(large language models), sentiment analyses etc. There are plenty of open source models and datasets on https://huggingface.co

This topic will be on R&D stage since it takes time to integrate. Let's discuss it here first and share resources. Then, we can add these features by creating a milestone.
