### ISSUE TITLE
epic(apps/ui): add control to storybook components

### ISSUE THREAD

**Issue by muhammed-gumus** [kamp-us/pano#676]
### What is this epic about?

Solve the attached error. Add controls for non-customizable storybook components
<img width="513" alt="Ekran Resmi 2023-08-18 14 41 59" src="https://github.com/kamp-us/monorepo/assets/86381278/e96ea2c3-6ec3-4842-9615-a6d13a07573e">

### Tasks for this epic

- [x] [Checkbox](https://github.com/kamp-us/monorepo/issues/669)
- [x] [DropDownMenu](https://github.com/kamp-us/monorepo/issues/670)
- [x] [Label](https://github.com/kamp-us/monorepo/issues/671)
- [x] [Select](https://github.com/kamp-us/monorepo/issues/672)
- [x] [Seperator](https://github.com/kamp-us/monorepo/issues/673)
- [x] [Toast](https://github.com/kamp-us/monorepo/issues/674)
- [ ] [AlertDialog](https://github.com/kamp-us/monorepo/issues/675)
