### ISSUE TITLE
JAVASCRIPT - 2/6 [ ÇEVİRİ LİSTESİ ]

### ISSUE THREAD

**Issue by gulech** [kamp-us/pano#831]
Bu liste [Full Stack JavaScript](https://www.theodinproject.com/paths/full-stack-javascript) kolunun [JavaScript](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript) bölümüne ait dersleri içermektedir. 

Orijinal proje sık sık güncellendiği için bazı farklılıklar olabilir. Bu listedeki metinler Türkçe Odin Projesi reposunda [bulunmaktadır.](https://github.com/kamp-us/monorepo/tree/dev/content/odin/javascript) Repoyu klonladıktan sonra çevirinizi bu İngilizce markdown dosyaları üzerinde yapınız.

### NASIL KATKI SAĞLAYABİLİRİM?

Siz de çevirmek istediğiniz sayfayı yorum yaparak belirtip hemen çevirmeye başlayabilirsiniz! [Çeviri rehberi](https://github.com/kamp-us/monorepo/blob/dev/content/odin/ceviri-rehberi.md)ni okumayı unutmayın.

   1. Issues kısmındaki [çeviri listelerinden](https://github.com/kamp-us/monorepo/issues?q=is%3Aopen+is%3Aissue+label%3Acontent%2Fodin) bir metin seçin.
   2. Issue altına çeviriyi üstlendiğinizi belirten bir yorumda bulunun.
   3. Bu repoyu bilgisayarınıza klonlayın.
   4. Klonladığınız klasör içinde üstlendiğiniz metnin markdown formatını bulun.
   5. Çeviriye başlamadan önce [çeviri rehberini](https://github.com/kamp-us/monorepo/blob/dev/content/odin/ceviri-rehberi.md) okuduğunuza emin olun.
   6. Çeviriyi tamamladıktan sonra son halini kontrol edin ve gerekli düzenlemeleri yapın.
   7. Bitmiş çeviriyi İngilizce yazılmış bir commit mesajıyla pull request olarak gönderin veya issue altına yoruma iliştirerek yollayın.
   8. Editör çevirinizi kontrol etsin ve yayına hazırlasın.
   9. Tebrikler! Bu maceraya atılacak olanlara önemli bir destekte bulundunuz. Artık adınız katkı sağlayanlar listesinde!

---

### JavaScript
- #### Introduction

  - [ ] [How this course will work?](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/introduction/how_this_course_will_work.md) ( @yunusolcar )
  - [ ] [A quick review](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/introduction/a_quick_review.md) ( @Doguhannilt )
 
- #### Organizing Your Javascript Code

  - [ ] [Organizing Your Javascript Code Introduction](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/organizing_your_javascript_code_introduction.md) ( @Doguhannilt )
  - [ ] [Objects and Object Constructors](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/objects_and_object_constructors.md)
  - [ ] [Project: Library](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/project_library.md) ( @Doguhannilt added by @igdiaysu ) PR: #849 
  - [ ] [Factory Functions and the Module Pattern](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/factory_functions_and_module_pattern.md)
  - [ ] [Project: Tic Tac Toe](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/project_tic_tac_toe.md) ( @Doguhannilt added by @igdiaysu ) PR: #850 
  - [ ] [Classes](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/classes.md) ( @Doguhannilt added by @igdiaysu ) PR: #851 
  - [ ] [ES6 Modules](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/es6_modules.md)
  - [ ] [Webpack](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/webpack.md)
  - [ ] [Project: Restaurant Page](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/project_restaurant_page.md)
  - [ ] [JSON](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/json.md) ( @Doguhannilt )
  - [ ] [OOP Principles](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/oop_principles.md) ( @yunusolcar added by @igdiaysu ) PR: #853 
  - [ ] [Project: Todo List](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/organizing_your_javascript_code/project_todo_list.md)
  
- #### JavaScript in the Real World

  - [ ] [Linting](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/javascript_in_the_real_world/linting.md) ( @Doguhannilt added by @igdiaysu ) PR: #899 
  - [ ] [Dynamic User Interface Interactions](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/javascript_in_the_real_world/dynamic_user_interface_interactions.md)
  - [ ] [Form Validation with JavaScript](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/javascript_in_the_real_world/form_validation_with_javascript.md)
  - [ ] [What is ES6?](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/javascript_in_the_real_world/what_is_es6.md) ( @Doguhannilt )

- #### Asynchronous JavaScript and APIs

  - [ ] [Asynchronous Code](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/asynchronous_javascript_and_apis/asynchronous_code.md) ( @ozkanturidi )
  - [ ] [Working with APIs](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/asynchronous_javascript_and_apis/working_with_apis.md)
  - [ ] [Async and Await](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/asynchronous_javascript_and_apis/async_and_await.md)
  - [ ] [Project: Weather App](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/asynchronous_javascript_and_apis/project_weather_app.md)

- #### A Bit of Computer Science

  - [ ] [A Very Brief Intro to CS](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/a_very_brief_intro_to_cs.md)
  - [ ] [Recursive Methods](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/recursive_methods.md)
  - [ ] [Project: Recursion](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/project_recursion.md)
  - [ ] [Time Complexity](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/time_complexity.md)
  - [ ] [Space Complexity](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/space_complexity.md)
  - [ ] [Common Data Structures and Algorithms](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/common_data_structures_algorithms.md)
  - [ ] [Project: Linked Lists](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/project_linked_lists.md)
  - [ ] [HashMap Data Structure](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/hash_map_data_structure.md)
  - [ ] [Project: HashMap](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/project_hash_map.md)
  - [ ] [Project: Binary Search Trees](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/project_binary_search_trees.md)
  - [ ] [Project: Knights Travails](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/computer_science/project_knights_travails.md)

- #### Testing JavaScript

  - [ ] [Testing Basics](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/testing_javascript/testing_basics.md) ( @Doguhannilt added by @igdiaysu ) PR: #898 
  - [ ] [Project: Testing Practice](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/testing_javascript/project_testing_practice.md)
  - [ ] [More Testing](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/testing_javascript/more_testing.md)
  - [ ] [Project: Battleship](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/testing_javascript/project_battleship.md)

- #### Finishing Up with JavaScript

  - [ ] [Conclusion](https://github.com/kamp-us/monorepo/blob/dev/content/odin/javascript/finishing_up_with_javascript/conclusion.md) ( @Doguhannilt added by @igdiaysu ) PR: #898

**Comment by yunusolcar** [comment]
<code>How this course will work?</code> ile başlamak isterim :)

**Comment by Doguhannilt** [comment]
`A quick review `alıyorum

Pull Request Gönderildi.

**Comment by ozkanturidi** [comment]
`Asynchronous Code` alabilirim :)

**Comment by Doguhannilt** [comment]
`JSON` çok sevdiğim bir konu olduğu için alıyorum ^^

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`Organizing Your Javascript Code Introduction`  alıyorum

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`What is Es6` Alıyorum

Pull Request Gönderildi.

**Comment by gulech** [comment]
> `Asynchronous Code` alabilirim :)

@ozkanturidi selam, katkı sağlamak istediğin için teşekkürler. Adını yazıyorum :)

**Comment by yunusolcar** [comment]
<code>OOP Principles</code> 'ı almak isterim

**Comment by Doguhannilt** [comment]
`Project: Library` alıyorum

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`Project: Tic Tac Toe` alıyorum

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`Classes` alıyorum

Pull Request Gönderildi.

**Comment by bavertorun** [comment]
`A Very Brief Intro to CS` alıyorum

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`Testing Basics` alıyorum

Pull Request Gönderildi.

**Comment by Doguhannilt** [comment]
`Conclusion` alıyorum

Pull Request Gönderildi

**Comment by Doguhannilt** [comment]
`Linting` alıyorum

Pull Request Gönderildi.
